export const REQUEST_BOARD_LIST_FROM_SPRING = 'REQUEST_BOARD_LIST_FROM_SPRING'
export const REQUEST_BOARD_FROM_SPRING = 'REQUEST_BOARD_FROM_SPRING'
export const REQUEST_PRODUCT_LIST_TO_SPRING = 'REQUEST_PRODUCT_LIST_TO_SPRING'